name: torch
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2022.2.1
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - cryptography=36.0.0
  - cudatoolkit=11.3.1
  - ffmpeg=4.3
  - freetype=2.11.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - idna=3.3
  - intel-openmp=2021.4.0
  - jpeg=9d
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgomp=9.3.0
  - libiconv=1.15
  - libidn2=2.3.2
  - libpng=1.6.37
  - libstdcxx-ng=9.3.0
  - libtasn1=4.16.0
  - libtiff=4.2.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libwebp=1.2.0
  - libwebp-base=1.2.0
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - numpy=1.21.2
  - numpy-base=1.21.2
  - olefile=0.46
  - openh264=2.1.0
  - openssl=1.1.1m
  - pillow=8.4.0
  - pip=21.2.2
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.7.11
  - pytorch=1.11.0
  - pytorch-mutex=1.0
  - readline=8.1
  - requests=2.27.1
  - setuptools=58.0.4
  - six=1.16.0
  - sqlite=3.36.0
  - tk=8.6.11
  - torchaudio=0.11.0
  - torchvision=0.12.0
  - typing_extensions=3.10.0.2
  - urllib3=1.26.8
  - wheel=0.37.0
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - appdirs==1.4.4
    - argcomplete==1.12.3
    - audioread==2.1.9
    - backcall==0.2.0
    - cycler==0.11.0
    - cython==0.29.28
    - debugpy==1.5.1
    - decorator==5.1.0
    - entrypoints==0.3
    - fonttools==4.33.2
    - importlib-metadata==4.8.2
    - ipykernel==6.6.0
    - ipython==7.30.1
    - jedi==0.18.1
    - joblib==1.1.0
    - jupyter-client==7.1.0
    - jupyter-core==4.9.1
    - kiwisolver==1.4.2
    - librosa==0.9.1
    - llvmlite==0.38.0
    - matplotlib==3.5.1
    - matplotlib-inline==0.1.3
    - nest-asyncio==1.5.4
    - numba==0.55.1
    - packaging==21.3
    - pandas==1.3.5
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pooch==1.6.0
    - prompt-toolkit==3.0.23
    - ptyprocess==0.7.0
    - pybind11==2.9.2
    - pygments==2.10.0
    - pyparsing==3.0.8
    - pyroomacoustics==0.6.0
    - python-dateutil==2.8.2
    - pytz==2022.1
    - pyyaml==6.0
    - pyzmq==22.3.0
    - resampy==0.2.2
    - scikit-learn==1.0.1
    - scipy==1.7.3
    - sklearn==0.0
    - soundfile==0.10.3.post1
    - threadpoolctl==3.0.0
    - torch==1.10.1
    - tornado==6.1
    - tqdm==4.64.0
    - traitlets==5.1.1
    - wcwidth==0.2.5
    - zipp==3.6.0
